import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  methodology: [{ type: "autogenerated", dirName: "1040-方法论" }],
  book: [{ type: "autogenerated", dirName: "1051-读书笔记" }],
  computer: [{ type: "autogenerated", dirName: "1052-计算机" }],
  gis: [{ type: "autogenerated", dirName: "1053-gis" }],
  english: [{ type: "autogenerated", dirName: "1054-英语" }],
  math: [{ type: "autogenerated", dirName: "1055-数学" }],
  tool: [{ type: "autogenerated", dirName: "1090-工具链" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
