import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  methodology: [{ type: "autogenerated", dirName: "20-方法论" }],
  ai: [{ type: "autogenerated", dirName: "30-ai" }],
  live: [{ type: "autogenerated", dirName: "40-生活" }],
  book: [{ type: "autogenerated", dirName: "50-读书" }],
  computer: [{ type: "autogenerated", dirName: "51-计算机" }],
  foundation: [{ type: "autogenerated", dirName: "52-专业基础" }],
  // work: [{ type: "autogenerated", dirName: "60-工作" }],
  tool: [{ type: "autogenerated", dirName: "80-工具" }],
  sop: [{ type: "autogenerated", dirName: "90-SOP" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
