import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	root: [{ type: "autogenerated", dirName: "." }],
	sop: [{ type: "autogenerated", dirName: "20-SOP" }],
	live: [{ type: "autogenerated", dirName: "30-生活" }],
	learn: [{ type: "autogenerated", dirName: "40-学习" }],
	ai: [{ type: "autogenerated", dirName: "50-AI" }],
	computer: [{ type: "autogenerated", dirName: "60-计算机" }],
	tool: [{ type: "autogenerated", dirName: "80-工具" }],
	backup: [{ type: "autogenerated", dirName: "90-存档" }],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
