/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  book: [{ type: "autogenerated", dirName: "1041_读书笔记" }],
  computer: [{ type: "autogenerated", dirName: "1042_计算机" }],
  gis: [{ type: "autogenerated", dirName: "1043_gis" }],
  english: [{ type: "autogenerated", dirName: "1044_英语" }],
  math: [{ type: "autogenerated", dirName: "1045_数学" }],
  tool: [{ type: "autogenerated", dirName: "1090_工具链" }],
};

module.exports = sidebars;
